<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>FunctionTest</RootNamespace>
        <TargetFrameworks>net8.0;net9.0;net8.0-windows</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Backend\Backend.csproj" />
      <ProjectReference Include="..\Bakend\Bakend.csproj" />
    </ItemGroup>

</Project>
