<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net8.0;net9.0;net8.0-windows</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="Npgsql" Version="9.0.3" />
      <PackageReference Include="StackExchange.Redis" Version="2.9.11" />
      <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    </ItemGroup>

</Project>
